<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'ai', language 'zh_tw', version '5.0'.
 *
 * @package     ai
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['acceptai'] = '接受並繼續';
$string['action'] = '動作';
$string['action_explain_text'] = '解釋文字';
$string['action_explain_text_desc'] = '解釋課程頁面上的文字內容。';
$string['action_explain_text_instruction'] = '您將收到來自使用者的文字輸入。您的任務是解釋所提供的文字。請遵循以下指導原則：
    1. 詳盡說明：擴展關鍵的觀念與概念，確保解釋能提供有意義的深度，而不是逐字重述原文。
    2. 簡化說明：將複雜的術語或概念拆解為簡單的部分，使其易於理解，適用於廣泛的受眾，包括學習者。
    3. 提供背景：解釋某件事情為何發生、如何運作或其目的為何。適當時，提供相關的例子或類比來增進理解。
    4. 邏輯組織：合理組織您的解釋，從基本觀念開始，再深入到更細節的部分。

重要指示:
    1. 只返回純文字摘要。
    2. 不要包含任何標記語法、問候語或客套話。
    3. 專注於清晰、簡潔與易於理解。

確保您的解釋容易閱讀，並有效傳達原文的要點。';
$string['action_generate_image'] = '生成圖片';
$string['action_generate_image_desc'] = '根據文字提示生成圖片。';
$string['action_generate_text'] = '生成文字';
$string['action_generate_text_desc'] = '根據文字提示生成文字內容。';
$string['action_generate_text_instruction'] = '您將收到來自使用者的文字輸入。您的任務是根據他們的要求生成文字。請遵循以下重要指示:
    1. 只返回純文字摘要。
    2. 不要包含任何標記語法、問候語或客套話。';
$string['action_summarise_text'] = '摘要文字';
$string['action_summarise_text_desc'] = '摘要課程頁面上的文字內容。';
$string['action_summarise_text_instruction'] = '您將收到來自使用者的文字輸入。您的任務是對提供的文字進行摘要。請遵循以下指導原則:
    1. 精簡：將長篇段落縮短為關鍵要點。
    2. 簡化：使複雜的資訊更容易理解，特別是對學習者來說。

重要指示:
    1. 只返回純文字摘要。
    2. 不要包含任何標記語法、問候語或客套話。
    3. 專注於清晰、簡潔和易於理解。

確保摘要易讀並有效地傳達原文的主要觀點。';
$string['action_translate_text'] = '翻譯文字';
$string['action_translate_text_desc'] = '將提供的文字從一種語言翻譯成另一種語言。';
$string['actionsettingprovider'] = '{$a} 動作設定';
$string['actionsettingprovider_desc'] = '這些設定控制 {$a->providername} 如何執行動作 {$a->actionname}。';
$string['actionsettings'] = '動作設定';
$string['actionsettings_desc'] = '這些設定用來控制此 AI 供應者實例的 AI 動作。';
$string['ai'] = 'AI';
$string['aiactionregister'] = 'AI 動作註冊';
$string['aiplacements'] = 'AI 功能位置';
$string['aipolicyacceptance'] = 'AI 政策同意';
$string['aipolicyregister'] = 'AI 政策註冊';
$string['aiproviders'] = 'AI 供應者';
$string['aireports'] = 'AI 報告';
$string['aiusage'] = 'AI 使用情況';
$string['aiusagepolicy'] = 'AI 使用政策';
$string['availableplacements'] = '選擇 AI 動作可使用的位置';
$string['availableplacements_desc'] = '功能位置（Placements）用於定義 AI 動作在網站中可使用的位置與方式。您可以透過設定選擇各位置可使用的動作。';
$string['availableproviders'] = '管理連接至您的 LMS 的 AI 供應者';
$string['availableproviders_desc'] = 'AI 供應者 通過「動作」如文字摘要或圖片生成，將 AI 功能添加到您的網站中。<br/>
您可以在其設定中管理每個供應者的動作。';
$string['btninstancecreate'] = '建立實例';
$string['btninstanceupdate'] = '更新實例';
$string['completiontokens'] = '完成 Tokens';
$string['completiontokens_help'] = '完成 tokens 是 AI 模型根據您的輸入生成的文字單位。較長的回應會使用更多的tokens，這可能會導致更高的費用。';
$string['configureprovider'] = '設定供應者實例';
$string['contentwatermark'] = 'Generated by AI';
$string['createnewprovider'] = '建立新的供應者實例';
$string['dateaccepted'] = '接受日期';
$string['declineaipolicy'] = '拒絕';
$string['enableglobalratelimit'] = '設定網站全域的請求速率限制';
$string['enableglobalratelimit_help'] = '限制 AI 供應者每小時在整個網站可接收的請求數量。';
$string['enableuserratelimit'] = '設定使用者請求速率限制';
$string['enableuserratelimit_help'] = '限制每個使用者每小時向 AI 供應者發送的請求數量。';
$string['error:actionnotfound'] = '動作「{$a}」不受支援。';
$string['error:providernotfound'] = '未找到 AI 供應者實例。';
$string['globalratelimit'] = '站點全域最大請求數量';
$string['globalratelimit_help'] = '每小時允許的站點全域請求數量。';
$string['manageaiplacements'] = '管理 AI 功能位置';
$string['manageaiproviders'] = '管理 AI 供應者';
$string['noproviders'] = '此動作不可用。此動作未設定任何 <a href="{$a}">AI 供應者</a> 。';
$string['placement'] = '功能位置';
$string['placementactionsettings'] = '動作';
$string['placementactionsettings_desc'] = '此位置可用的 AI 動作。';
$string['placementsettings'] = '針對功能位置的設定';
$string['placementsettings_desc'] = '這些設定控制該 AI 功能位置如何與 AI 服務連接，以及相關的操作。';
$string['privacy:metadata:ai_action_explain_text'] = '儲存用戶請求解釋文字的表格。';
$string['privacy:metadata:ai_action_explain_text:completiontoken'] = '用於解釋文字的完成tokens。';
$string['privacy:metadata:ai_action_explain_text:fingerprint'] = '表示模型與內容狀態/版本的唯一哈希值。';
$string['privacy:metadata:ai_action_explain_text:generatedcontent'] = '根據輸入提示，AI 模型生成的實際文字。';
$string['privacy:metadata:ai_action_explain_text:prompt'] = '解釋文字請求的提示。';
$string['privacy:metadata:ai_action_explain_text:prompttokens'] = '用於解釋文字的提示tokens。';
$string['privacy:metadata:ai_action_explain_text:responseid'] = '回應的 ID。';
$string['privacy:metadata:ai_action_generate_image'] = '儲存用戶請求圖片生成的表格。';
$string['privacy:metadata:ai_action_generate_image:aspectratio'] = '生成圖片的長寬比。';
$string['privacy:metadata:ai_action_generate_image:numberimages'] = '生成的圖片數量。';
$string['privacy:metadata:ai_action_generate_image:prompt'] = '圖片生成請求的提示。';
$string['privacy:metadata:ai_action_generate_image:quality'] = '生成圖片的品質。';
$string['privacy:metadata:ai_action_generate_image:revisedprompt'] = '生成圖片的修訂提示。';
$string['privacy:metadata:ai_action_generate_image:sourceurl'] = '生成圖片的來源網址。';
$string['privacy:metadata:ai_action_generate_image:style'] = '生成圖片的風格。';
$string['privacy:metadata:ai_action_generate_text'] = '儲存用戶請求文字生成的表格。';
$string['privacy:metadata:ai_action_generate_text:completiontoken'] = '用於生成文字的完成 tokens。';
$string['privacy:metadata:ai_action_generate_text:fingerprint'] = '表示模型與內容狀態/版本的唯一哈希值。';
$string['privacy:metadata:ai_action_generate_text:generatedcontent'] = '根據輸入提示，AI 模型生成的實際文字。';
$string['privacy:metadata:ai_action_generate_text:prompt'] = '文字生成請求的提示。';
$string['privacy:metadata:ai_action_generate_text:prompttokens'] = '用於生成文字的提示 tokens。';
$string['privacy:metadata:ai_action_generate_text:responseid'] = '回應的 ID。';
$string['privacy:metadata:ai_action_register'] = '儲存用戶請求動作的表格。';
$string['privacy:metadata:ai_action_register:actionid'] = '動作請求的 ID。';
$string['privacy:metadata:ai_action_register:actionname'] = '請求的動作名稱。';
$string['privacy:metadata:ai_action_register:model'] = '用於生成回應的模型。';
$string['privacy:metadata:ai_action_register:provider'] = '處理請求的供應者名稱。';
$string['privacy:metadata:ai_action_register:success'] = '動作請求的狀態。';
$string['privacy:metadata:ai_action_register:timecompleted'] = '請求的完成時間。';
$string['privacy:metadata:ai_action_register:timecreated'] = '請求的建立時間。';
$string['privacy:metadata:ai_action_register:userid'] = '發出請求的使用者 ID。';
$string['privacy:metadata:ai_action_summarise_text'] = '儲存用戶請求文字摘要的表格。';
$string['privacy:metadata:ai_action_summarise_text:completiontoken'] = '用於摘要文字的完成 tokens。';
$string['privacy:metadata:ai_action_summarise_text:fingerprint'] = '表示模型與內容狀態/版本的唯一哈希值。';
$string['privacy:metadata:ai_action_summarise_text:generatedcontent'] = '根據輸入提示，AI 模型生成的實際文字。';
$string['privacy:metadata:ai_action_summarise_text:prompt'] = '文字摘要請求的提示。';
$string['privacy:metadata:ai_action_summarise_text:prompttokens'] = '用於摘要文字的提示 tokens。';
$string['privacy:metadata:ai_action_summarise_text:responseid'] = '回應的 ID。';
$string['privacy:metadata:ai_policy_register'] = '儲存每位使用者 AI 政策接受狀態的表格。';
$string['privacy:metadata:ai_policy_register:contextid'] = '儲存資料的上下文 ID。';
$string['privacy:metadata:ai_policy_register:timeaccepted'] = '使用者接受 AI 政策的時間。';
$string['privacy:metadata:ai_policy_register:userid'] = '儲存資料的使用者 ID。';
$string['prompttokens'] = '提示 tokens';
$string['prompttokens_help'] = '提示 tokens 是構成您傳送給 AI 模型的輸入文字單位。較長的輸入會使用更多的 tokens，這可能會導致更高的費用。';
$string['provider'] = '提供者';
$string['provideractionsettings'] = '動作';
$string['provideractionsettings_desc'] = '選擇並設定 {$a} 在您的網站上可以執行的動作。';
$string['providerinstanceactionupdated'] = '{$a} 動作設定已更新';
$string['providerinstancecreated'] = '{$a} AI 提供者實例已建立。';
$string['providerinstancedelete'] = '刪除 AI 提供者實例';
$string['providerinstancedeleteconfirm'] = '您即將刪除 AI 提供者實例 {$a->name} ({$a->provider})。您確定嗎？';
$string['providerinstancedeleted'] = '{$a} AI 提供者實例已刪除。';
$string['providerinstancedeletefailed'] = '無法刪除 {$a} AI 提供者實例。該提供者可能正在使用中，或者有資料庫問題。請檢查該提供者是否啟用，或聯繫您的資料庫管理員以尋求幫助。';
$string['providerinstancedisablefailed'] = '無法停用 AI 提供者實例。該提供者可能正在使用中，或者有資料庫問題。請檢查該提供者是否啟用，或聯繫您的資料庫管理員以尋求幫助。';
$string['providerinstanceupdated'] = '{$a} AI 提供者實例已更新。';
$string['providermoveddown'] = '{$a} 向下移動。';
$string['providermovedup'] = '{$a} 向上移動。';
$string['providername'] = '實例名稱';
$string['providers'] = '提供者';
$string['providersettings'] = '設定';
$string['providertype'] = '選擇 AI 提供者外掛';
$string['timegenerated'] = '生成時間';
$string['unknownvalue'] = '—';
$string['userpolicy'] = '<h4><strong>歡迎使用全新的 AI 功能！</strong></h4>
<p>此人工智慧（AI）功能僅基於外部大型語言模型（LLM），旨在提升您的學習與教學體驗。在開始使用這些 AI 服務之前，請閱讀此使用政策。</p>
<h4><strong>AI 生成內容的準確性</strong></h4>
<p>AI 可以提供有用的建議和資訊，但其準確性可能有所不同。您應該始終再次核對提供的資訊，確保其準確、完整並適合您的特定情況。</p>
<h4><strong>您的資料如何處理</strong></h4>
<p>此 AI 功能使用外部大型語言模型（LLM）。如果您使用此功能，您所分享的任何資訊或個人資料將依照這些 LLM 的隱私政策處理。我們建議您閱讀他們的隱私政策，了解他們將如何處理您的資料。此外，您與 AI 功能的互動記錄可能會保存在此網站中。</p>
<p>如果您對您的資料如何處理有疑問，請向您的老師或學習機構查詢。</p>
<p>繼續使用即表示您了解並同意此政策。</p>';
$string['userratelimit'] = '每位使用者的最大請求次數';
$string['userratelimit_help'] = '每位使用者每小時允許的請求次數。';
